# Generated by Django 2.0.1 on 2019-10-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_auto_20191020_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completiondate', models.DateField()),
                ('datejoining', models.DateField()),
                ('coursefee', models.IntegerField()),
                ('instructor', models.CharField(max_length=20)),
                ('aadhar', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.User')),
            ],
        ),
    ]
