# Generated by Django 2.0.1 on 2019-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
    ]
