# Generated by Django 2.0.1 on 2019-10-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_auto_20191020_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerstatus',
            field=models.CharField(default='ongoing', max_length=9),
        ),
    ]
